name: Deploy to EC2 with Docker

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Stop existing container (if any)
        run: |
          docker stop node-app || true
          docker rm node-app || true

      - name: Build Docker image
        run: docker build -t node-app .

      - name: Run Docker container
        run: docker run -d -p 80:3000 --name node-app node-app
